-- Write your PostgreSQL query statement below
SELECT CONTEST_ID,ROUND(100*COUNT(U.USER_ID)/((SELECT COUNT(*) FROM USERS))::NUMERIC,2
) AS PERCENTAGE FROM REGISTER R INNER JOIN USERS U
ON R.USER_ID=U.USER_ID
GROUP BY CONTEST_ID ORDER BY PERCENTAGE DESC,CONTEST_ID ASC;