-- Write your PostgreSQL query statement below
SELECT CONTEST_ID, ROUND(100*COUNT(*)/((SELECT COUNT(USER_ID) FROM USERS))::NUMERIC,2) AS PERCENTAGE FROM REGISTER R LEFT JOIN USERS U 
ON U.USER_ID=R.USER_ID GROUP BY CONTEST_ID ORDER BY PERCENTAGE DESC , CONTEST_ID ;