-- Write your PostgreSQL query statement below
SELECT S.USER_ID, ROUND(AVG(
    CASE 
    WHEN ACTION = 'confirmed' THEN 1
    ELSE 0 END
)::NUMERIC,2) CONFIRMATION_RATE
 FROM SIGNUPS S LEFT JOIN CONFIRMATIONS C
ON S.USER_ID=C.USER_ID GROUP BY S.USER_ID;