-- Write your PostgreSQL query statement below
WITH S AS (SELECT PRODUCT_ID , MIN(YEAR) AS FIRST_YEAR
FROM SALES GROUP BY PRODUCT_ID)
SELECT S.PRODUCT_ID,FIRST_YEAR,QUANTITY,PRICE
FROM SALES S1 INNER JOIN S 
ON S1.PRODUCT_ID=S.PRODUCT_ID AND S1.YEAR=S.FIRST_YEAR;