-- Write your PostgreSQL query statement below
WITH A2 AS (
    SELECT PLAYER_ID,MIN(EVENT_DATE) AS FIRST_DATE FROM ACTIVITY
    GROUP BY PLAYER_ID
) 
SELECT ROUND(COUNT(DISTINCT A1.PLAYER_ID)::NUMERIC/(SELECT COUNT(DISTINCT PLAYER_ID) FROM ACTIVITY),2) AS FRACTION FROM ACTIVITY A1 INNER JOIN A2 
ON A1.PLAYER_ID=A2.PLAYER_ID  WHERE A1.EVENT_DATE-1=A2.FIRST_DATE;