-- Write your PostgreSQL query statement below

WITH P AS (
    SELECT PRODUCT_ID,10 AS PRICE FROM PRODUCTS
),
U AS (
SELECT PRODUCT_ID, MAX(CHANGE_DATE) FROM
PRODUCTS WHERE CHANGE_DATE<='2019-08-16' GROUP BY PRODUCT_ID)
SELECT U.PRODUCT_ID,P1.NEW_PRICE AS PRICE FROM U INNER JOIN PRODUCTS P1 ON U.PRODUCT_ID=P1.PRODUCT_ID AND P1.CHANGE_DATE=U.MAX
UNION SELECT * FROM P WHERE PRODUCT_ID NOT IN (SELECT PRODUCT_ID FROM U);