-- Write your PostgreSQL query statement below

WITH P AS (
    SELECT PRODUCT_ID,10 AS PRICE FROM PRODUCTS
),
U AS (
SELECT DISTINCT ON(PRODUCT_ID) PRODUCT_ID , NEW_PRICE,CHANGE_DATE FROM
PRODUCTS WHERE CHANGE_DATE<='2019-08-16' ORDER BY PRODUCT_ID,CHANGE_DATE DESC)
SELECT U.PRODUCT_ID,U.NEW_PRICE AS PRICE FROM U 
UNION SELECT * FROM P WHERE PRODUCT_ID NOT IN (SELECT PRODUCT_ID FROM U);