-- Write your PostgreSQL query statement below
WITH Y AS (
    SELECT EMPLOYEE_ID,department_id
    FROM EMPLOYEE WHERE PRIMARY_FLAG='Y'
),
 E1 AS(
SELECT EMPLOYEE_ID FROM EMPLOYEE 
GROUP BY EMPLOYEE_ID HAVING COUNT(DEPARTMENT_ID)=1)
SELECT E2.EMPLOYEE_ID,E2.department_id FROM E1 INNER JOIN EMPLOYEE E2 ON E1.EMPLOYEE_ID=E2.EMPLOYEE_ID 
UNION SELECT * FROM Y;