-- Write your PostgreSQL query statement below
WITH D AS (
SELECT A.TURN,SUM(B.WEIGHT) AS S FROM QUEUE A INNER JOIN QUEUE B
ON A.TURN>=B.TURN GROUP BY A.TURN HAVING SUM(B.WEIGHT)<=1000 ORDER BY TURN DESC LIMIT 1)
SELECT PERSON_NAME FROM QUEUE Q INNER JOIN D
ON Q.TURN=D.TURN;