-- Write your PostgreSQL query statement below
WITH C AS (
    SELECT 'Low Salary' AS category
    UNION ALL
    SELECT 'Average Salary'
    UNION ALL
    SELECT 'High Salary'
),
S AS (
SELECT (
    CASE
    WHEN INCOME<20000 THEN 'Low Salary'
    WHEN INCOME BETWEEN 20000 AND 50000 THEN 'Average Salary'
    ELSE 'High Salary' END
) AS CATEGORY, COUNT(*) AS ACCOUNTS_COUNT FROM ACCOUNTS
GROUP BY CATEGORY)
SELECT * FROM  S UNION SELECT CATEGORY,0 AS ACCOUNTS_COUNT FROM C WHERE CATEGORY NOT IN (SELECT CATEGORY FROM S) GROUP BY CATEGORY;