-- Write your PostgreSQL query statement below
SELECT A.MACHINE_ID,ROUND(AVG(B.TIMESTAMP - A.TIMESTAMP)::NUMERIC,3) AS PROCESSING_TIME  FROM ACTIVITY B INNER JOIN ACTIVITY A 
ON A.MACHINE_ID=B.MACHINE_ID AND A.PROCESS_ID=B.PROCESS_ID WHERE A.ACTIVITY_TYPE = 'start' AND B.ACTIVITY_TYPE = 'end' GROUP BY A.MACHINE_ID; 