-- Write your PostgreSQL query statement below
SELECT MACHINE_ID,ROUND(AVG(
    CASE 
    WHEN ACTIVITY_TYPE='start' THEN (-2*TIMESTAMP)
    ELSE 2*TIMESTAMP
    END 
)::NUMERIC,3) AS PROCESSING_TIME FROM ACTIVITY GROUP BY MACHINE_ID;