-- Write your PostgreSQL query statement below
SELECT A1.MACHINE_ID,ROUND(AVG(A2.timestamp-A1.timestamp)::NUMERIC,3) AS PROCESSING_TIME FROM ACTIVITY A1 INNER JOIN ACTIVITY A2
ON A1.MACHINE_ID = A2.MACHINE_ID AND A1.ACTIVITY_TYPE<>A2.ACTIVITY_TYPE WHERE A2.ACTIVITY_TYPE = 'end' 
GROUP BY A1.MACHINE_ID;