-- Write your PostgreSQL query statement below
SELECT TO_CHAR(T1.TRANS_DATE,'YYYY-MM') AS MONTH,
T1.COUNTRY,COUNT(*) AS TRANS_COUNT,SUM(
    CASE
    WHEN T1.STATE = 'approved' then 1 else 0 end
) AS APPROVED_COUNT,
SUM(T1.AMOUNT) AS TRANS_TOTAL_AMOUNT,
SUM(
    CASE
    WHEN T1.STATE = 'approved' then T1.AMOUNT else 0 end
) AS APPROVED_TOTAL_AMOUNT
 FROM TRANSACTIONS T1 
GROUP BY MONTH,T1.COUNTRY;