-- Write your PostgreSQL query statement below
SELECT TO_CHAR(T1.TRANS_DATE,'yyyy-mm') AS MONTH,T1.COUNTRY, 
COUNT(TO_CHAR(T1.TRANS_DATE,'yyyy-mm')) AS TRANS_COUNT,
SUM(
    CASE WHEN T1.STATE = 'approved' THEN 1 ELSE 0 END
) AS APPROVED_COUNT,SUM(T1.AMOUNT) AS TRANS_TOTAL_AMOUNT,SUM(
    CASE WHEN T1.STATE = 'approved' THEN T1.AMOUNT ELSE 0 END
) AS APPROVED_TOTAL_AMOUNT
FROM TRANSACTIONS T1
GROUP BY MONTH,T1.COUNTRY;