-- Write your PostgreSQL query statement below
WITH D AS (
SELECT * FROM ORDERS 
WHERE TO_CHAR(ORDER_DATE,'YYYY-MM')='2020-02')
, DD AS (
    SELECT P.PRODUCT_NAME,SUM(D.UNIT) AS UNIT FROM PRODUCTS P INNER JOIN D 
    ON P.PRODUCT_ID=D.PRODUCT_ID
    GROUP BY P.PRODUCT_NAME,D.PRODUCT_ID HAVING SUM(D.UNIT)>=100
)
SELECT * FROM DD ;
