-- Write your PostgreSQL query statement below
WITH MR AS (
    SELECT USER_ID,COUNT(*) AS CNT FROM
    MovieRating GROUP BY USER_ID ORDER BY CNT DESC 
),
UR AS (
SELECT NAME AS RESULTS FROM MR INNER JOIN USERS U
ON MR.USER_ID=U.USER_ID ORDER BY CNT DESC,NAME LIMIT 1)
,
RR AS (
    SELECT MOVIE_ID,(AVG(RATING)) AS AV FROM MovieRating WHERE TO_CHAR(CREATED_AT,'YYYY-MM')='2020-02' 
    GROUP BY MOVIE_ID ORDER BY AV DESC 
),
RRR AS (
SELECT TITLE AS RESULTS FROM RR INNER JOIN MOVIES M
ON RR.MOVIE_ID=M.MOVIE_ID ORDER BY AV DESC,TITLE LIMIT 1)
SELECT * FROM UR UNION ALL SELECT * FROM RRR;