-- Write your PostgreSQL query statement below
SELECT SELL_DATE,COUNT(DISTINCT PRODUCT) AS NUM_SOLD,STRING_AGG(DISTINCT PRODUCT,',' ORDER BY PRODUCT) AS PRODUCTS
 FROM ACTIVITIES A
GROUP BY SELL_DATE;