-- Write your PostgreSQL query statement below
SELECT ROUND(SUM(I.TIV_2016)::NUMERIC,2) AS TIV_2016 FROM INSURANCE I
WHERE tiv_2015 IN (SELECT tiv_2015 FROM INSURANCE I2 WHERE I.PID<>I2.PID)
AND (LAT,LON) NOT IN (SELECT LAT,LON FROM INSURANCE I2 WHERE I.PID<>I2.PID);