-- Write your PostgreSQL query statement below
WITH S AS (
    SELECT * FROM STUDENTS CROSS JOIN SUBJECTS
)
SELECT S.STUDENT_ID,S.STUDENT_NAME,S.SUBJECT_NAME,COUNT(E.STUDENT_ID) AS ATTENDED_EXAMS  FROM S LEFT JOIN EXAMINATIONS E
ON S.STUDENT_ID=E.STUDENT_ID AND S.SUBJECT_NAME=E.SUBJECT_NAME
GROUP BY S.STUDENT_ID,S.STUDENT_NAME,S.SUBJECT_NAME;