-- Write your PostgreSQL query statement below
SELECT S.STUDENT_ID,S.STUDENT_NAME,SB.SUBJECT_NAME,COUNT(E.SUBJECT_NAME) AS ATTENDED_EXAMS FROM (STUDENTS S CROSS JOIN SUBJECTS SB)
LEFT JOIN EXAMINATIONS E ON E.STUDENT_ID=S.STUDENT_ID AND E.SUBJECT_NAME=SB.SUBJECT_NAME
GROUP BY S.STUDENT_ID,SB.SUBJECT_NAME,S.STUDENT_NAME;