-- Write your PostgreSQL query statement below
SELECT E1.EMPLOYEE_ID,E1.NAME,COUNT(*) AS REPORTS_COUNT,ROUND(AVG(E2.AGE)) AS AVERAGE_AGE FROM EMPLOYEES E1 INNER JOIN EMPLOYEES E2
ON E1.EMPLOYEE_ID=E2.REPORTS_TO GROUP BY E1.EMPLOYEE_ID,E1.NAME ORDER BY EMPLOYEE_ID;