-- Write your PostgreSQL query statement below
WITH L AS (
    SELECT L1.ID,L1.NUM FROM LOGS L1 INNER JOIN LOGS L2
    ON L1.NUM=L2.NUM AND L1.ID=L2.ID+1
)
SELECT DISTINCT L1.NUM AS ConsecutiveNums  FROM LOGS L1 INNER JOIN L
ON L1.NUM=L.NUM AND L1.ID=L.ID+1;