-- Write your PostgreSQL query statement below
WITH LOGSR AS (SELECT *, RANK() OVER(ORDER BY ID) AS RK FROM LOGS)
SELECT DISTINCT L1.NUM AS ConsecutiveNums FROM LOGSR L1 INNER JOIN LOGSR L2 
ON L1.NUM=L2.NUM AND L1.RK=L2.RK+1
INNER JOIN LOGSR L3
ON L2.RK=L3.RK+1 AND L1.NUM=L3.NUM;