-- Write your PostgreSQL query statement below
SELECT CUSTOMER_ID, SUM(
    CASE
    WHEN AMOUNT IS NULL THEN 1
    ELSE 0
    END
) AS COUNT_NO_TRANS
 FROM VISITS V LEFT JOIN TRANSACTIONS T ON V.VISIT_ID = T.VISIT_ID
 GROUP BY CUSTOMER_ID HAVING SUM(
    CASE
    WHEN AMOUNT IS NULL THEN 1
    ELSE 0
    END
)>0;