-- Write your PostgreSQL query statement below
SELECT DEPARTMENT,EMPLOYEE,SALARY FROM (
    SELECT *
    FROM(
SELECT D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE , SALARY, DENSE_RANK() OVER(PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) AS RK
FROM EMPLOYEE E LEFT JOIN DEPARTMENT D
ON E.DEPARTMENTID = D.ID) WHERE RK<4);