-- Write your PostgreSQL query statement below
WITH D AS(
SELECT departmentId ID,NAME,SALARY, DENSE_RANK() OVER(PARTITION BY departmentId ORDER BY SALARY DESC) AS RK FROM EMPLOYEE E
ORDER BY ID)
SELECT DE.NAME AS DEPARTMENT,D.NAME AS EMPLOYEE,SALARY FROM D INNER JOIN DEPARTMENT DE
ON D.ID=DE.ID WHERE RK<4;