-- Write your PostgreSQL query statement below
WITH D AS (
    SELECT DISTINCT VISITED_ON,SUM(AMOUNT) AS AMOUNT,AVG(AMOUNT::numeric) AS AVERAGE_AMOUNT 
    FROM CUSTOMER GROUP BY VISITED_ON
)
SELECT D.visited_on,SUM(D2.AMOUNT) AS AMOUNT,ROUND(AVG(D2.AMOUNT)::NUMERIC,2) AS AVERAGE_AMOUNT 
FROM D INNER JOIN D D2
ON D.VISITED_ON-D2.VISITED_ON BETWEEN 0 AND 6
GROUP BY D.visited_on HAVING COUNT(D2.VISITED_ON)=7 
ORDER BY D.VISITED_ON;