-- Write your PostgreSQL query statement below
WITH C AS (
    SELECT VISITED_ON, SUM(AMOUNT) AS AMOUNT
    FROM CUSTOMER GROUP BY VISITED_ON
) 
SELECT A.VISITED_ON,ROUND(SUM(B.AMOUNT)::NUMERIC,2) as amount,ROUND(AVG(B.AMOUNT)::NUMERIC,2) as average_amount
FROM C A, C B WHERE A.VISITED_ON-B.VISITED_ON BETWEEN 0 AND 6  GROUP BY A.VISITED_ON
HAVING COUNT(*)>6 ORDER BY a.visited_on;