-- Write your PostgreSQL query statement below
SELECT QUERY_NAME,ROUND(AVG(RATING/POSITION::numeric)::NUMERIC,2) AS QUALITY,
ROUND(100*AVG(
    CASE 
    WHEN RATING <3 THEN 1
    ELSE 0 END
)::NUMERIC,2) AS POOR_QUERY_PERCENTAGE
FROM QUERIES Q
GROUP BY QUERY_NAME;