-- Write your PostgreSQL query statement below
SELECT ROUND(100*AVG(
    CASE
    WHEN D.ORDER_DATE = customer_pref_delivery_date THEN 1
    ELSE 0 
    END
)::numeric,2 ) AS immediate_percentage FROM (
    SELECT CUSTOMER_ID,MIN(ORDER_DATE) as ORDER_DATE FROM DELIVERY GROUP BY CUSTOMER_ID
) AS D INNER JOIN DELIVERY ON D.CUSTOMER_ID = DELIVERY.CUSTOMER_ID AND D.ORDER_DATE=DELIVERY.ORDER_DATE;