-- Write your PostgreSQL query statement below
SELECT PROJECT_ID,ROUND(AVG(EXPERIENCE_YEARS)::NUMERIC,2) AS AVERAGE_YEARS FROM PROJECT P INNER JOIN EMPLOYEE E
ON P.EMPLOYEE_ID=E.EMPLOYEE_ID GROUP BY PROJECT_ID;